# Generated by Django 5.2 on 2025-05-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='loyalty_ponts',
            new_name='loyalty_points',
        ),
    ]
