# Generated by Django 5.2 on 2025-05-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_loyalty_ponts_user_loyalty_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcard',
            old_name='current_amount',
            new_name='current_ammount',
        ),
    ]
