# Generated by Django 5.2 on 2025-05-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_orderitem_total_ammount_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='type',
            field=models.CharField(blank=True, choices=[('milk', 'milk'), ('coffe', 'coffe')], max_length=100, null=True),
        ),
    ]
