# Generated by Django 5.2 on 2025-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_option_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(blank=True, choices=[('milk', 'milk'), ('coffe', 'coffee')], max_length=100, null=True),
        ),
    ]
